#!/bin/bash

source version.sh

docker run -d \
  --name taskbird \
  -p 8010:80 \
  -e "TASKBIRD_SECRET_KEY=$TASKBIRD_SECRET_KEY" \
  -e "TASKBIRD_HOST=$TASKBIRD_HOST" \
  -e "TASKBIRD_DATABASE_HOST=$TASKBIRD_DATABASE_HOST" \
  -e "TASKBIRD_DATABASE_NAME=$TASKBIRD_DATABASE_NAME" \
  -e "TASKBIRD_DATABASE_USER=$TASKBIRD_DATABASE_USER" \
  -e "TASKBIRD_DATABASE_PASSWORD=$TASKBIRD_DATABASE_PASSWORD" \
  -e "TASKBIRD_GOOGLE_OAUTH_KEY=$TASKBIRD_GOOGLE_OAUTH_KEY" \
  -e "TASKBIRD_GOOGLE_OAUTH_SECRET=$TASKBIRD_GOOGLE_OAUTH_SECRET" \
  -e "TASKBIRD_ADMIN_NAME=$TASKBIRD_ADMIN_NAME" \
  -e "TASKBIRD_ADMIN_EMAIL=$TASKBIRD_ADMIN_EMAIL" \
  "clintonmorrison/projects:taskbird-$VERSION"

